apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-service
  labels:
    app: webapi-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapi-service
  template:
    metadata:
      labels:
        app: webapi-service
    spec:
      containers:
      - name: webapi-service
        image: webapi-service-docker
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        
        
---
apiVersion: v1
kind: Service
metadata:
  name: webapi-service
  namespace: default
  labels:
    app: webapi-service
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30080
  selector:
    app: webapi-service

