apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-np
  labels:
    app: webapi-np
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapi-np
  template:
    metadata:
      labels:
        app: webapi-np
    spec:
      containers:
      - name: webapi-np
        image: webapi
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: webapi-np
  namespace: default
  labels:
    app: webapi-np
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: webapi-np

